/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-05 05:09:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    /* div{border:1px solid red;} */\r\n");
      out.write("    #footer{\r\n");
      out.write("        width:80%;\r\n");
      out.write("        height:200px;\r\n");
      out.write("        margin:auto;\r\n");
      out.write("        margin-top:50px;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-1{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        height:20%;\r\n");
      out.write("        border-top:1px solid lightgray;\r\n");
      out.write("        border-bottom:1px solid lightgray;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-2{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        height:80%;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-1, #footer-2{\r\n");
      out.write("        padding-left:50px\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #footer-1 > a{\r\n");
      out.write("        text-decoration:none;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        margin:10px;\r\n");
      out.write("        line-height: 40px;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-2>p{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding:10px;\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("    }\r\n");
      out.write("    #p2{\r\n");
      out.write("        text-align:center;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("        <div id=\"footer-1\">\r\n");
      out.write("            <a href=\"#\">이용약관</a> | \r\n");
      out.write("            <a href=\"#\">개인정보취급방침</a> | \r\n");
      out.write("            <a href=\"#\">인재채용</a> | \r\n");
      out.write("            <a href=\"#\">고객센터</a> \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"footer-2\">\r\n");
      out.write("            <p id=\"p1\">\r\n");
      out.write("                1관 : 서울특별시 강남구 테헤란로 1 UNI 빌딩 2F, 3F, 4F, 5F <br>\r\n");
      out.write("                2관 : 서울특별시 강남구 테헤란로 2 UNI 빌딩 4F, 5F, 7F <br>\r\n");
      out.write("               \r\n");
      out.write("             \r\n");
      out.write("            </p>\r\n");
      out.write("            <p id=\"p2\">Copyright ⓒ UNI Information Educational Institute All Right Reserved</p>     \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
